env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  "@typescript-eslint/no-non-null-assertion":
    - off
  no-control-regex: off
  no-constant-condition: off
  no-underscore-dangle: off
  no-useless-escape: off
  camelcase: off
  no-process-exit: off
  no-empty: off
  new-cap:
    - 2
    - newIsCap: true
      capIsNew: true
      newIsCapExceptions: []
      capIsNewExceptions: []
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false